# Generated by Django 5.2.12 on 2026-04-23 19:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria de Conteúdo',
                'verbose_name_plural': 'Categorias de Conteúdo',
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
            options={
                'verbose_name': 'Cronograma da Turma',
                'verbose_name_plural': 'Cronogramas das Turmas',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_no_drive', models.CharField(blank=True, max_length=100, null=True)),
                ('link_no_drive', models.URLField(blank=True, null=True)),
                ('ementa_URL', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_classroom', models.CharField(blank=True, max_length=255, null=True)),
                ('id_calendar', models.CharField(blank=True, max_length=255, null=True)),
                ('planilha_URL', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_user', models.CharField(choices=[('G', 'Gestão'), ('A', 'Aluno'), ('P', 'Professor')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='ConteudoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_no_drive', models.CharField(max_length=255)),
                ('link_no_drive', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.conteudocategoria')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.disciplina')),
            ],
            options={
                'verbose_name': 'Conteúdo de Disciplina',
                'verbose_name_plural': 'Conteúdos de Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='CronogramaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista_evento', models.DateField()),
                ('conteudos', models.ManyToManyField(blank=True, related_name='cronograma_items', to='academic_services.conteudodisciplina')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.cronograma')),
            ],
            options={
                'verbose_name': 'Item do Cronograma',
                'verbose_name_plural': 'Itens do Cronograma',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovacao_automatica', models.BooleanField(default=True)),
                ('data_da_postagem', models.DateTimeField()),
                ('id_post_classroom', models.CharField(blank=True, max_length=255, null=True)),
                ('cronograma_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.cronogramaitem')),
            ],
            options={
                'verbose_name': 'Agendamento de Postagem',
                'verbose_name_plural': 'Agendamentos de Postagem',
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('cronograma_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic_services.cronogramaitem')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('disponibilidade', models.TextField(blank=True, null=True)),
                ('google_calendar_id', models.CharField(blank=True, help_text='ID da agenda Google do professor', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cronograma_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_services.cronogramaitem')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.disciplina')),
                ('prof_real', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_lecionadas', to='academic_services.professor')),
                ('prof_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_titular', to='academic_services.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.turma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('status_troca', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Recusada', 'Recusada')], default='Pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.aula')),
                ('prof_subst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituicoes_aceitas', to='academic_services.professor')),
                ('prof_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_solicitadas', to='academic_services.professor')),
            ],
            options={
                'verbose_name': 'Substituição de Aula',
                'verbose_name_plural': 'Substituições de Aulas',
            },
        ),
        migrations.CreateModel(
            name='TemplateCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='cronograma',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_services.templatecronograma'),
        ),
        migrations.CreateModel(
            name='TemplateCronogramaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_aula', models.CharField(help_text="Ex: 'Aula 1 - Introdução'", max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.templatecronograma')),
            ],
        ),
        migrations.AddField(
            model_name='cronogramaitem',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.templatecronogramaitem'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='academic_services.turma'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_matriculas', to='academic_services.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_services.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
